import { App } from '@/types';

export const APPS: App[] = [
  {
    id: 'gmail',
    name: 'Gmail',
    description: 'Send, read, and manage emails',
    icon: '📧',
    category: 'Productivity',
    connected: false,
    actions: [
      { id: 'send_email', name: 'Send Email', description: 'Send an email to a recipient' },
      { id: 'read_emails', name: 'Read Emails', description: 'List recent emails' },
      { id: 'search', name: 'Search', description: 'Search emails by query' },
    ],
  },
  {
    id: 'slack',
    name: 'Slack',
    description: 'Send messages and manage channels',
    icon: '💬',
    category: 'Communication',
    connected: false,
    actions: [
      { id: 'send_message', name: 'Send Message', description: 'Send a message to a channel' },
      { id: 'list_channels', name: 'List Channels', description: 'List all channels' },
      { id: 'search', name: 'Search', description: 'Search messages' },
    ],
  },
  {
    id: 'github',
    name: 'GitHub',
    description: 'Manage repos, issues, and PRs',
    icon: '🐙',
    category: 'Development',
    connected: false,
    actions: [
      { id: 'create_issue', name: 'Create Issue', description: 'Create a new issue' },
      { id: 'list_repos', name: 'List Repos', description: 'List repositories' },
      { id: 'create_pr', name: 'Create PR', description: 'Create a pull request' },
    ],
  },
  {
    id: 'notion',
    name: 'Notion',
    description: 'Create and manage pages and databases',
    icon: '📝',
    category: 'Productivity',
    connected: false,
    actions: [
      { id: 'create_page', name: 'Create Page', description: 'Create a new page' },
      { id: 'search', name: 'Search', description: 'Search workspace' },
      { id: 'update_page', name: 'Update Page', description: 'Update an existing page' },
    ],
  },
  {
    id: 'google_calendar',
    name: 'Google Calendar',
    description: 'Manage events and schedules',
    icon: '📅',
    category: 'Productivity',
    connected: false,
    actions: [
      { id: 'create_event', name: 'Create Event', description: 'Create a new event' },
      { id: 'list_events', name: 'List Events', description: 'List upcoming events' },
      { id: 'delete_event', name: 'Delete Event', description: 'Delete an event' },
    ],
  },
  {
    id: 'linear',
    name: 'Linear',
    description: 'Project management and issue tracking',
    icon: '📋',
    category: 'Development',
    connected: false,
    actions: [
      { id: 'create_issue', name: 'Create Issue', description: 'Create a new issue' },
      { id: 'list_issues', name: 'List Issues', description: 'List issues' },
      { id: 'update_status', name: 'Update Status', description: 'Change issue status' },
    ],
  },
  {
    id: 'twitter',
    name: 'X (Twitter)',
    description: 'Post tweets and manage your profile',
    icon: '🐦',
    category: 'Social',
    connected: false,
    actions: [
      { id: 'post_tweet', name: 'Post Tweet', description: 'Publish a tweet' },
      { id: 'search', name: 'Search', description: 'Search tweets' },
      { id: 'dm', name: 'Send DM', description: 'Send a direct message' },
    ],
  },
  {
    id: 'stripe',
    name: 'Stripe',
    description: 'Manage payments and subscriptions',
    icon: '💳',
    category: 'Finance',
    connected: false,
    actions: [
      { id: 'create_payment', name: 'Create Payment', description: 'Create a payment intent' },
      { id: 'list_customers', name: 'List Customers', description: 'List all customers' },
      { id: 'refund', name: 'Refund', description: 'Issue a refund' },
    ],
  },
  {
    id: 'youtube',
    name: 'YouTube',
    description: 'Search and manage videos',
    icon: '▶️',
    category: 'Social',
    connected: false,
    actions: [
      { id: 'search', name: 'Search', description: 'Search videos' },
      { id: 'upload', name: 'Upload Video', description: 'Upload a video' },
      { id: 'analytics', name: 'Analytics', description: 'Get channel analytics' },
    ],
  },
  {
    id: 'discord',
    name: 'Discord',
    description: 'Send messages and manage servers',
    icon: '🎮',
    category: 'Communication',
    connected: false,
    actions: [
      { id: 'send_message', name: 'Send Message', description: 'Send a message' },
      { id: 'list_members', name: 'List Members', description: 'List server members' },
    ],
  },
  {
    id: 'airtable',
    name: 'Airtable',
    description: 'Manage bases, tables, and records',
    icon: '📊',
    category: 'Productivity',
    connected: false,
    actions: [
      { id: 'create_record', name: 'Create Record', description: 'Create a new record' },
      { id: 'list_records', name: 'List Records', description: 'List records' },
      { id: 'update_record', name: 'Update Record', description: 'Update a record' },
    ],
  },
  {
    id: 'resend',
    name: 'Resend',
    description: 'Transactional email API',
    icon: '✉️',
    category: 'Communication',
    connected: false,
    actions: [
      { id: 'send_email', name: 'Send Email', description: 'Send an email' },
      { id: 'list_emails', name: 'List Emails', description: 'List sent emails' },
    ],
  },
];

export const CATEGORIES = [
  'All',
  'Productivity',
  'Communication',
  'Development',
  'Social',
  'Finance',
];
